### PR TITLE
Change output record bound to an implicit check

### PR DESCRIPTION
**Pull request by laughedelic**

### CODE REVIEW

**Comment by eparejatobes** [comment]
@laughedelic what's the status of this?

**Comment by laughedelic** [comment]
I'm not sure it should be merged. It was done when I had an issue in MG7 when something related to this bound was crashing the REPL, but it appears that it was just the REPL problem. The bound works as is. So I don't think we need to introduce another implicit for commands building.

**Comment by eparejatobes** [comment]
OK thanks. Closing then.

**Comment by laughedelic** [comment]
Ok, but don't delete the branch, please.

**Comment by eparejatobes** [comment]
Made a tag `archive/enhancement/out-rec-bound`. Tell me if you want to keep the branch anyway

**Pull request closed without merging**
