### PR TITLE
IgBLAST output parsing

### PR DESCRIPTION
**Pull request by eparejatobes**
- [x] Add the summary table: *Alignment summary between query and top germline V gene hit (from, to, length, matches, mismatches, gaps, percent identity)*
- [x] code for splitting lines by headers, getting tables
- [ ] keep the same commands, have different apply methods for each reasonable combination
- [x] Parsers for each output field
- [x] have reasonable names for fields and records; they're a mess now
- [x] support for TCR beta output

### CODE REVIEW

**Comment by eparejatobes** [comment]
For reference: [IgBLAST paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3692102/pdf/gkt382.pdf)

**Comment by eparejatobes** [comment]
@rtobes @marina-manrique 

This is part of the igblastn output:

```

# Alignment summary between query and top germline V gene hit (from, to, length, matches, mismatches, gaps, percent identity)
FR1-IMGT	1	54	54	49	5	0	90.7
CDR1-IMGT	55	78	24	17	7	0	70.8
FR2-IMGT	79	129	51	45	6	0	88.2
CDR2-IMGT	130	153	24	17	7	0	70.8
FR3-IMGT	154	267	114	97	17	0	85.1
CDR3-IMGT (germline)	268	268	1	1	0	0	100
Total	N/A	N/A	268	226	42	0	84.3
```

Questions:

1. what are all does FR[1-3] rows?
2. do we want them?

**Comment by eparejatobes** [comment]
Note to self:

The methods for building expressions will not use BLAST expressions or anything. We just generate a `Seq[String]` reusing part of the available infrastructure.

**Comment by eparejatobes** [comment]
This is almost working for TCR alpha.

**Comment by eparejatobes** [comment]
Given my comment [here](https://github.com/ohnosequences/blast-api/pull/50#issuecomment-278622786) I'm refactoring the cdrX records, which will be fields.

**Comment by rtobes** [comment]
> what are all does FR[1-3] rows?
> do we want them?
As we talked these rows include Annotation data for the BCR and TCR that we need to show for each UMI-consensus-sequence

**Comment by eparejatobes** [comment]
I have added a test for TCR beta output. The only thing that's left is grouping the code in tests into methods.

**Comment by eparejatobes** [comment]
This is done.

**Pull request merged**
