### PR TITLE
Add options for blastx

### PR DESCRIPTION
**Pull request by eparejatobes**
At the moment you can change only `num_threads`. Wee need this for https://github.com/era7bio/metaGacu/pull/28#issuecomment-199948477

### CODE REVIEW

**Comment by eparejatobes** [comment]
@laughedelic I think this is enough for what you need

**Comment by eparejatobes** [comment]
If this works for you, feel free to merge and release. The only other change is that reference DB is now a set of files.

**Comment by laughedelic** [comment]
Cool, thanks!

**Comment by laughedelic** [comment]
@eparejatobes could you review the list of `ValidOutputFields` for blastx? It's rather short and I cannot use the same output format as the MG7's default one for blastn (in https://github.com/era7bio/metaGacu/pull/28)

**Comment by eparejatobes** [comment]
https://github.com/ohnosequences/blast-api/releases/tag/v0.6.1

**Pull request merged**
