### PR TITLE
Remove the task option

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by laughedelic** [comment]
>  just provide predefined groups of options here, and remove the task option

👍 

But this requires some changes to the general API: now you will have several "defaults" (tasks) and one has to be chosen explicilty.

**Comment by eparejatobes** [comment]
Not really; tasks are only a set of option values. Usage: `blastn.defaults updateWith task.megablast`

**Comment by laughedelic** [comment]
> Setting the task for the blastn application changes the default value of a number of command-line arguments, such as the word size, but also the default scoring parameters for insertions, deletions, and mismatches.

The thing is that some options don't have a "default default" value, i.e. some value independent of tasks (like `penalty`/`reward`), so they cannot be put in defaults, but have to be set in tasks. If we remove all such ambiguous options from the defaults sets, then I'm fine with this way. But then they have to be arguments, right? This separation is quite inconvenient..

**Comment by eparejatobes** [comment]
I didn't quite understand that. What I propose is

1. set as defaults the values corresponding to the "task" that we consider default (like `blastn` in the case of `blastn`
2. if needed/requested, create for each task a set of option values, according to http://www.ncbi.nlm.nih.gov/books/NBK279675/

**Comment by laughedelic** [comment]
Well, ok. I guess choosing one task as default is the easiest way.

**Comment by eparejatobes** [comment]
Fine, then I'm going to merge this and open a new issue for task support.

**Comment by laughedelic** [comment]
Why did you suddenly raise this issue, btw?

**Comment by eparejatobes** [comment]
As a maintainer, I want to push for a stable, comprehensive library :+1: :grinning: :memo:

**Comment by laughedelic** [comment]
Here, you forgot this one: :trollface:

**Pull request merged**
